arquivo = open("palavras.txt", "w")
arquivo.write("banana\n")
arquivo.write("maça\n")
arquivo.write("abacaxi\n")
arquivo.write("pessego\n")
arquivo.write("laranja\n")
arquivo.write("morango\n")
arquivo.write("jabuticaba\n")
arquivo.write("amora\n")
arquivo.write("melancia\n")